### ISSUE TITLE
Update to Django 4.0

### ISSUE THREAD

**Issue by brianjbuck** [brianjbuck/drf_orjson_renderer#13]
Currently RestFramework does not support Django 4.0 deprecation of `pytz`:

```
/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/rest_framework/fields.py:32: in <module>
    from pytz.exceptions import InvalidTimeError
E   ModuleNotFoundError: No module named 'pytz'
```
Update to Django 4.0 when Restframework is released.

**Comment by Zagrebelin** [comment]
Hello,

Dec, 13 DRF released 3.13 version with a django 4.0 support
https://github.com/encode/django-rest-framework/pull/8178
