### ISSUE TITLE
Python 3.6 dropped support is really necessary?

### ISSUE THREAD

**Issue by onegreyonewhite** [brianjbuck/drf_orjson_renderer#15]
Probably I’ve not seen any commits, but what the benefit the python 3.6 support drop provide gave?

**Comment by brianjbuck** [comment]
@onegreyonewhite:

>orjson supports CPython 3.7, 3.8, 3.9, and 3.10
https://github.com/ijl/orjson#readme

**Comment by onegreyonewhite** [comment]
> @onegreyonewhite:
> 
> > orjson supports CPython 3.7, 3.8, 3.9, and 3.10
> > https://github.com/ijl/orjson#readme

I think it would be wiser to set up requirements in the project depending on the version of python. Version 3.6 is still relevant, as long as there is official support for CentOS 7.
