### ISSUE TITLE
Dependency resolution fails with Django versions 4.0.x

### ISSUE THREAD

**Issue by duebbert** [brianjbuck/drf_orjson_renderer#20]
Dependency resolution fails when installing drf-orjson-renderer with the latest Django version (4.0.6). The pinned version is too specific. 

I would suggest changing it from ` "django>=3.2,<=4.0"` to  `"django>=3.2,<4.1"` and re-releasing to PyPi.

**Comment by onegreyonewhite** [comment]
@sidmitra are there any plans to solve this problem? And while there are disputes, 4.1 has already been released...
