### ISSUE TITLE
Add CI configuration

### ISSUE THREAD

**Issue by johnthagen** [brianjbuck/drf_orjson_renderer#7]
Could add Travis CI or GitHub actions to automatically run the test suite on all code for each new commit or PR that is submitted.

The [`drf_ujson2`](https://github.com/Amertz08/drf_ujson2) repository has a good setup that could be used as an example.

- [`tox.ini`](https://github.com/Amertz08/drf_ujson2/blob/master/tox.ini)
- [`travis.yml`](https://github.com/Amertz08/drf_ujson2/blob/master/.travis.yml)

**Comment by brianjbuck** [comment]
Done.
